<a href="https://colab.research.google.com/github/meoowqt/pythonBigDataLab/blob/main/LW1_numpy_Vechkanova_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Задание 1. Генератор СЛАУ

Необходимо написать программу, которая получает на вход СЛАУ и, если она имеет ненулевое решение, гененрирует заданное количество СЛАУ, имеющих то же решение, причем матрицы должны отличаться.

Подход к проерке и генерации данных выбирается исключительно на ваше умотрение, главное чтобы каждую полученную матрицу можно было решить с помощью того же вектора X, который является решением исходной СЛАУ

In [ ]:
import numpy as np

def generate_new_slu(A, b, num_slu):
    # Создаем список новых СЛАУ
    new_slus = []
    x = np.linalg.solve(A, b)
    # Генерируем новые векторы A
    for i in range(num_slu):
        # Генерируем случайный вектор b
        A_new = A + np.random.normal(0, 1000, A.shape)
        while np.linalg.det(A_new) == 0:
          A_new = A + np.random.normal(0, 1000, A.shape)
        b_new = np.matmul(A_new, x)
        x_new = np.linalg.solve(A_new, b_new)
        new_slus.append((A_new, b_new, x_new))
    return new_slus

# Исходная СЛАУ
A = np.random.sample((3, 3))
b = np.random.sample((3))

print("Исходные матрицы:")
print(f"A = {A}")
print(f"b = {b}")
print(f"x = {np.linalg.solve(A, b)}")
print()
# Генерируем список новых СЛАУ с тем же решением
new_slus = generate_new_slu(A, b, 3)

# Выводим новые СЛАУ

print("Сгенерированные матрицы:")
for A_new, b_new, x_new in new_slus:
    print(f"A_new = {A_new}")
    print(f"b_new = {b_new}")
    print(f"x_new = {x_new}")
    print()

Исходные матрицы:
A = [[0.81216117 0.64164749 0.94181558]
 [0.27729598 0.16720236 0.33794836]
 [0.64552757 0.09297385 0.40994132]]
b = [0.98783047 0.78676865 0.20636206]
x = [-4.49798969 -5.84978243  8.91302016]

Сгенерированные матрицы:
A_new = [[-482.87883179  561.4449423   484.23351433]
 [-492.50858918  275.68559776  -49.78992962]
 [-206.95216119 1164.70326107 1456.91461632]]
b_new = [3203.63632021  158.81914125 7103.11735765]
x_new = [-4.49798969 -5.84978243  8.91302016]

A_new = [[  468.59165405 -1465.45907236  -512.10836916]
 [ -565.07147558 -1264.78922758 -1155.11705916]
 [ -134.81871246 -1808.12882429  -735.6585657 ]]
b_new = [1900.46409222 -355.15416176 4626.63378409]
x_new = [-4.49798969 -5.84978243  8.91302016]

A_new = [[  328.92731349   670.64093453 -2495.48157674]
 [-1028.92524346   -10.06338584   863.47047611]
 [  475.6450766     90.35763911   160.62713355]]
b_new = [-27644.89282537  12383.0935126   -1236.34629926]
x_new = [-4.49798969 -5.84978243  8.91302016]



###Задание 2. OLAP-куб
Сгенерировать OLAP-куб, в котором зафиксированы продажи товаров в розничной сети по магазинам. Оси: 0: ID группы товаров 1: ID магазина 2: день месяца, в котором осуществляются продажи (предположим у нас в OLAP-кубе собраны продажи за месяц). Содержимое ячейки: продажи в тыс. рублей данной категории товаров в данном магазине в данный день.

Рекомендуется сгенерировать статистически-правдопододные данные в ячейках. К примеру, будет странно, если продажи одной и той же группы товаров в соседние дни будут представлять из себя "белый шум". Пусть будет какой-то правдоподобное распределение на ваш вкус. Также продажи одних и тех же групп товаров в разных магазинах не могут отличаться в сотни и тысячи раз, максимум в разы. Подумайте как это обыграть используя различные функции генерации случайных чисел + "смекалку". "Правильного" решения тут нет, любое решение подойдёт, если будет понятно, что вы хотя бы попытались применить интеллект )

[Про OLAP-куб](http://www.olap.ru/basic/alpero2i.asp)

In [ ]:
import numpy as np
import pandas as pd

# Параметры куба
num_product_groups = 10  # Количество групп товаров
num_stores = 6           # Количество магазинов
num_days = 30            # Количество дней в месяце

# Функция для генерации данных продаж
def generate_sales_data(num_product_groups, num_stores, num_days):
    # Генерируем сетку всех возможных комбинаций
    product_groups, stores, days = np.meshgrid(
        np.arange(1, num_product_groups + 1),
        np.arange(1, num_stores + 1),
        np.arange(1, num_days + 1),
        indexing='ij'
    )
    # Генерируем продажи
    sales_data = np.random.normal(
        np.random.uniform(50, 80, size=(num_product_groups, num_stores, num_days)),
        np.random.uniform(3, 3, size=(num_product_groups, num_stores, num_days)))
    if (sales_data.any() <= 0) :
        sales_data = np.random.normal(np.random.uniform(50, 80, size=(num_product_groups, num_stores, num_days)),
        np.random.uniform(5, 5, size=(num_product_groups, num_stores, num_days)))
    return product_groups.flatten(), stores.flatten(), days.flatten(), sales_data.flatten()

# Генерация данных
product_groups, stores, days, sales_data = generate_sales_data(num_product_groups, num_stores, num_days)

# Создание DataFrame
df = pd.DataFrame({
    'ID группы товаров': product_groups,
    'ID магазина': stores,
    'День месяца': days,
    'Продажи в тыс. рублей': sales_data
})

# Вывод DataFrame
df


ID группы товаров  ID магазина  День месяца  Продажи в тыс. рублей
0                     1            1            1              71.973979
1                     1            1            2              64.838091
2                     1            1            3              59.631431
3                     1            1            4              62.279172
4                     1            1            5              73.534261
...                 ...          ...          ...                    ...
1795                 10            6           26              65.555832
1796                 10            6           27              51.141664
1797                 10            6           28              60.848637
1798                 10            6           29              56.590480
1799                 10            6           30              62.157085

[1800 rows x 4 columns]